# Generated by Django 2.2 on 2019-06-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0002_auto_20190419_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='tems',
            new_name='teams',
        ),
    ]
