# Generated by Django 2.2 on 2019-08-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0011_remove_workout_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='includeInFinalResults',
            field=models.BooleanField(default=True),
        ),
    ]
