# Generated by Django 2.2 on 2019-10-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0014_auto_20191010_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description_extended',
            field=models.TextField(null=True),
        ),
    ]
