# Generated by Django 2.2 on 2019-10-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0015_workout_description_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description_extended',
            field=models.TextField(blank=True, null=True),
        ),
    ]
