# Generated by Django 2.2 on 2020-02-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('description_extended', models.TextField(blank=True, null=True)),
                ('scoringStyle', models.CharField(choices=[('W', 'weight'), ('R', 'reps'), ('T', 'time')], default='T', max_length=1)),
                ('includeInFinalResults', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Event')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Event'),
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Team')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Workout')),
            ],
            options={
                'unique_together': {('team', 'workout', 'event')},
            },
        ),
    ]
