# Generated by Django 2.2 on 2019-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='time',
        ),
        migrations.AddField(
            model_name='score',
            name='minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
