# Generated by Django 2.2 on 2019-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0003_auto_20190611_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='scoringStyle',
            field=models.CharField(choices=[('W', 'weight'), ('R', 'reps'), ('T', 'time')], default='T', max_length=1),
        ),
    ]
