# Generated by Django 2.2 on 2019-06-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0005_auto_20190617_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='teams',
            new_name='team',
        ),
    ]
