# Generated by Django 2.2 on 2019-08-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0008_auto_20190805_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Division'),
            preserve_default=False,
        ),
    ]
