# Generated by Django 2.2 on 2019-08-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deschutesDemoScores', '0010_auto_20190807_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
    ]
