# Generated by Django 2.2 on 2019-10-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('deschutesDemoScores', '0013_auto_20190905_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamID',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Team', to_field='team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deschutesDemoScores.Team', to_field='team'),
        ),
    ]
